defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "manuals"
    values:
      layout: "manual"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "base"

collections:
  authors:
    output: true
  manuals:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

source: src
