jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - env:
          JEKYLL_ENV: production
        name: build_jekyll
        run: bundle exec jekyll build

name: jekyll

on: [push]
