jobs:
  build:
    env:
      WORKING_DIRECTORY: jekyll
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: npm_install
        run: npm clean-install
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: bundle_install
        run: bundle install
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - env:
          JEKYLL_ENV: production
        name: jekyll_build
        run: bundle exec jekyll build
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: upload_artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: _site

  deploy:
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    name: deploy
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: download_artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: npm_install
        run: npm install --save-dev netlify-cli
      - name: netlify_deploy
        run: npx netlify deploy --auth ${{ env.NETLIFY_AUTH_TOKEN }} --dir dist/_site --site ${{ env.NETLIFY_SITE_ID }}

name: integration

on: [push]
