jobs:
  build:
    env:
      WORKING_DIRECTORY: jekyll
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: bundle_install
        run: bundle install
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - env:
          JEKYLL_ENV: production
        name: jekyll_build
        run: bundle exec jekyll build
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: upload_artifact
        uses: actions/upload-artifact@v1
        with:
          name: drop
          path: jekyll/_site

  deploy:
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    name: deploy
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: download_artifact
        uses: actions/download-artifact@v1
        with:
          name: drop
      - name: npm_install
        run: npm install netlify-cli
      - if: github.event_name == 'pull_request'
        name: netlify_deploy_pullrequest
        run: npx netlify deploy --dir drop --message="$(date --iso-8601='seconds') :: ${GITHUB_WORKFLOW} \#${GITHUB_RUN_NUMBER} :: ${GITHUB_HEAD_REF##*/}"
      - if: github.event_name != 'pull_request'
        name: netlify_deploy_push
        run: npx netlify deploy --dir drop --prod --message="$(date --iso-8601='seconds') :: ${GITHUB_WORKFLOW} \#${GITHUB_RUN_NUMBER} :: ${GITHUB_REF##*/}"

name: integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
